name: datingapp
description: "A premium dating & social app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.2.1

  # Networking
  dio: ^5.4.3

  # Images
  cached_network_image: ^3.3.1

  # Fonts
  google_fonts: ^6.2.1

  # UI Scaling
  flutter_screenutil: ^5.9.3

  # Shimmer
  shimmer: ^3.0.0

  # Pull to refresh
  pull_to_refresh: ^2.0.0

  # SVG
  flutter_svg: ^2.0.10+1

  # Date/Time
  intl: ^0.19.0

  # DI
  get_it: ^7.7.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
